DROP DATABASE IF EXISTS "ProjectDB";
DROP ROLE IF EXISTS admin;


CREATE DATABASE "ProjectDB";


CREATE ROLE admin
WITH LOGIN
PASSWORD 'admin123';

GRANT ALL PRIVILEGES ON DATABASE "ProjectDB" TO admin;